name: After Release

on:
  release:
    types: [published]

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Got tag name ${{ github.event.release.body }}"
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C03TT70H0LE
          slack-text: Name "${{ github.event.release.name  }}" Description "${{ github.event.release.body }}"
